# name: Github CICP Pipeline Terraform

# On: workfloe_dispatch
# permissions:
#   id-token: write
#   contents: read
# jobs:
#   terraform-job:
#     runs_on: self-hosted or 
#     runs_on: ubuntu-latest #for github hosted runner
#     steps:
#     -name: checkout
#      uses: actions/checkout@v5.0.0

#     -name:terraform init
#      id: init
#      run: terraform init-input=false
#      working-directory: .github/workflows
     
#     -name:terraform fmt
#      id: fmt
#      run: terraform fmt-input=false
#      continue-on-error: true
#      working-directory: .github/workflows
     
#     -name:terraform validate
#      id: validate
#      run: terraform validate-no-color
#      continue-on-error: true
#      working-directory: .github/workflows 
     
#     -name:terraform plan
#      id: plan
#      run: terraform plan-no-color-input=false
#      continue-on-error: true
#      working-directory: .github/workflows 

 # pipeline with jobs & conditions for terraform

name: Terraform Pipeline

on:
  workflow_dispatch:     # manual trigger ke liye
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  terraform_plan:
    name: Terraform Init, Fmt, Validate & Plan
    runs-on: self-hosted   # ya 'ubuntu-latest' agar GitHub runner use karna ho
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Uncomment agar Azure login chahiye toh
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: .github/workflows

      - name: Terraform Fmt
        run: terraform fmt -input=false
        continue-on-error: true
        working-directory: .github/workflows

      - name: Terraform Validate
        run: terraform validate -no-color
        continue-on-error: true
        working-directory: .github/workflows

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: .github/workflows

  manual_approval:
    name: Manual Validation
    runs-on: ubuntu-latest    # GitHub hosted runner
    needs: terraform_plan
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: your-github-username   # Apna GitHub username yahan daal
          minimum-approvals: 1
          issue-title: "Approve Terraform Apply"
          issue-body: "Approve to continue to Terraform Apply step."

  terraform_apply:
    name: Terraform Apply
    runs-on: self-hosted
    needs: manual_approval
    if: github.ref == 'refs/heads/main'    # Sirf main branch pe chalega
    environment: dev   # ya prod, jo bhi environment chahiye
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (again to sync state)
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

    
   
