name: CICD PIPELINE

on:
  workflow_dispatch

jobs:
  terraform-tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Anup
        run: echo "hello Anup"
      - name: Greet Rajnish
        run: echo "hello Rajnish"

  
